[project]
name = "sdocx"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
conformance = [
    "numpy>=2.4.2",
    "pillow>=12.1.1",
    "pymupdf>=1.28.2",
]
dev = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "ruff>=0.15.5",
]
